{{- if .Values.ingress.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    {{- include "kubenurse.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "kubenurse.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ .Values.ingress.url }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "kubenurse.fullname" . }}
            port:
              number: {{ .Values.service.port }}
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.ingress.url }}
    {{- with .Values.ingress.tlsSecretName }}
    secretName: {{ . }}
    {{- end -}}
{{- end -}}